// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkuApsiKB9CJf9oixcnwKBcqf0mlYSnvw',
    appId: '1:884574318102:web:0769da6a620e802548cf37',
    messagingSenderId: '884574318102',
    projectId: 'todo-af8dc',
    authDomain: 'todo-af8dc.firebaseapp.com',
    databaseURL: 'https://todo-af8dc-default-rtdb.firebaseio.com',
    storageBucket: 'todo-af8dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbvMrFVSrQCWlEtTrUd8nUYkyV7CD_XDU',
    appId: '1:884574318102:android:a037841adfeb021548cf37',
    messagingSenderId: '884574318102',
    projectId: 'todo-af8dc',
    databaseURL: 'https://todo-af8dc-default-rtdb.firebaseio.com',
    storageBucket: 'todo-af8dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQarLLlD81FwM-Sewfg1Pc8uhbdgnH920',
    appId: '1:884574318102:ios:bf75f4e81860caa048cf37',
    messagingSenderId: '884574318102',
    projectId: 'todo-af8dc',
    databaseURL: 'https://todo-af8dc-default-rtdb.firebaseio.com',
    storageBucket: 'todo-af8dc.appspot.com',
    iosClientId: '884574318102-pctpkn82d3123eufha433tnkghigh0fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicationdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQarLLlD81FwM-Sewfg1Pc8uhbdgnH920',
    appId: '1:884574318102:ios:bf75f4e81860caa048cf37',
    messagingSenderId: '884574318102',
    projectId: 'todo-af8dc',
    databaseURL: 'https://todo-af8dc-default-rtdb.firebaseio.com',
    storageBucket: 'todo-af8dc.appspot.com',
    iosClientId: '884574318102-pctpkn82d3123eufha433tnkghigh0fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicationdata',
  );
}
